server.port: 7003
server.error.include-message: always

spring.application.name: task-service

app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.data.mongodb:
  uri: mongodb+srv://workflow-task:vu4m9DaL0mFvNrrt@cluster-project.nqglq.mongodb.net/taskDB?retryWrites=true&w=majority

logging:
  level:
    root: INFO
    workflow: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.config.activate.on-profile: docker

server.port: 8080

app.eureka-server: eureka

